CREATE TABLE IF NOT EXISTS public.alert_chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id VARCHAR(128) NOT NULL,
    sender_employee_id VARCHAR(50) NOT NULL REFERENCES public.employee_accounts(employee_id) ON DELETE CASCADE,
    sender_name VARCHAR(150) NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    message_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_alert_chat_messages_sender_role
        CHECK (sender_role IN ('HEAD', 'System Admin', 'Responder'))
);

CREATE INDEX IF NOT EXISTS idx_alert_chat_messages_incident_created
    ON public.alert_chat_messages (incident_id, created_at, message_id);

ALTER TABLE public.alert_chat_messages ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON TABLE public.alert_chat_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.alert_chat_messages_message_id_seq TO service_role;